app/controllers/CommodityCodeBestMatchController.scala, app/controllers/InformationAboutYourItemController.scala, app/controllers/LegalChallengeController.scala, app/controllers/RegisterBusinessRepresentingController.scala, app/controllers/SelectApplicationTypeController.scala, app/controllers/SimilarItemCommodityCodeController.scala, app/controllers/SupportingInformationController.scala, app/controllers/WhenToSendSampleController.scala, app/controllers/WhichBestDescribesYouController.scala, app/controllers/YesNoBehaviour.scala, app/controllers/YesNoController.scala, app/navigation/Navigator.scala, app/views/components/answer_row.scala.html, app/views/components/answer_section.scala.html, test/unit/controllers/CheckYourAnswersControllerSpec.scala, test/unit/controllers/CommodityCodeBestMatchControllerSpec.scala, test/unit/controllers/InformationAboutYourItemControllerSpec.scala, test/unit/controllers/LegalChallengeControllerSpec.scala, test/unit/controllers/SelectApplicationTypeControllerSpec.scala, test/unit/controllers/SimilarItemCommodityCodeControllerSpec.scala, test/unit/controllers/SupportingInformationControllerSpec.scala, test/unit/controllers/WhenToSendSampleControllerSpec.scala, test/unit/controllers/WhichBestDescribesYouControllerSpec.scala
Trader can review and edit answers involving multiple pages
=> DIT 563 check you answers fix

app/views/commodityCodeBestMatch.scala.html, app/views/commodityCodeDigits.scala.html, app/views/commodityCodeRulingReference.scala.html, app/views/components/input_radio.scala.html, app/views/components/input_text.scala.html, app/views/components/input_textarea.scala.html, app/views/components/input_yes_no.scala.html, app/views/confidentialInformation.scala.html, app/views/informationAboutYourItem.scala.html, app/views/legalChallenge.scala.html, app/views/legalChallengeDetails.scala.html, app/views/previousCommodityCode.scala.html, app/views/selectApplicationType.scala.html, app/views/supportingInformation.scala.html, app/views/supportingInformationDetails.scala.html, app/views/supportingMaterialFileList.scala.html, app/views/whenToSendSample.scala.html, app/views/whichBestDescribesYou.scala.html
Ensuring labels for input fields (areas) and legends for radio buttons
=> Accessibility changes

app/config/FrontendAppConfig.scala, app/controllers/SignOutController.scala, app/views/main_template.scala.html, app/views/session_expired.scala.html, app/views/unauthorised.scala.html, conf/app.routes, conf/application.conf, conf/messages.en, test/unit/base/SpecBase.scala, test/unit/controllers/SignOutControllerSpec.scala, test/unit/views/SessionExpiredViewSpec.scala, test/unit/views/UnauthorisedViewSpec.scala, test/unit/views/behaviours/ViewBehaviours.scala
Also
- removes 32 year session timeout config
- clears user data (cache) on logout
=> Dit 1070 - timeout warning dialog

app/assets/stylesheets/bindingtarifftraderfrontend-app.scss
Fix for the Beta banner for responsive design
=> DIT-1300b: fixed beta banner

app/views/components/select.scala.html, app/views/main_template.scala.html
- also updated select input to constrain width and prevent flash of different width prior to js autocomplete loading
=> DIT-1912 - Remove duplicated js

app/views/similarItemCommodityCode.scala.html
ARIA work in this ticket fixed as part of DIT-1854
=> DIT-1869 Uncombined h1 and legend, similar item

app/views/govuk_wrapper.scala.html, app/views/registerBusinessRepresenting.scala.html, app/views/registeredAddressForEori.scala.html
Also moved GTM code out of head
=> DIT-1875 Remove unrequired fieldset

app/assets/stylesheets/partials/_upload_help.scss
This reverts commit fca047e0f4e7d6633b5f2418c142765fef92d84d.
=> Revert "DIT-1853 fixed remove link overflow issue on mobile device"

app/utils/PostcodeValidator.scala, conf/messages.en, test/unit/forms/RegisterBusinessRepresentingFormProviderSpec.scala, test/unit/forms/RegisteredAddressForEoriFormProviderSpec.scala, test/unit/forms/behaviours/FieldBehaviours.scala, test/unit/utils/PostcodeValidatorSpec.scala
DIT-2099: fix bug when postcode is lower case
=> DIT-2099: fix bug for max postcode length

app/connectors/BindingTariffClassificationConnector.scala, app/models/Case.scala, test/unit/connectors/BindingTariffClassificationConnectorSpec.scala
Must be merged after https://github.com/hmrc/binding-tariff-classification/pull/137
=> DIT-2235 Don't show migrated cases on the applications page

app/connectors/BindingTariffClassificationConnector.scala, app/connectors/BindingTariffFilestoreConnector.scala, app/connectors/DataCacheConnector.scala, app/connectors/EmailConnector.scala, app/connectors/PdfGeneratorServiceConnector.scala, test/unit/connectors/BindingTariffClassificationConnectorSpec.scala, test/unit/connectors/BindingTariffFilestoreConnectorSpec.scala, test/unit/connectors/ConnectorTest.scala, test/unit/connectors/EmailConnectorSpec.scala, test/unit/connectors/MongoCacheConnectorSpec.scala, test/unit/connectors/PdfGeneratorServiceConnectorSpec.scala, test/unit/utils/TestMetrics.scala
This builds on #196, adding metrics collection to connectors.
=> DIT-2287 Add metrics collection to connectors

build.sbt
I added the silencer plugin to suppress warnings from generated code like routes files and views.
=> Suppress warnings from generated code

app/controllers/CheckYourAnswersController.scala, app/controllers/IsSampleHazardousController.scala, app/forms/IsSampleHazardousFormProvider.scala, app/mapper/CaseRequestMapper.scala, app/models/Application.scala, app/pages/IsSampleHazardousPage.scala, app/utils/CheckYourAnswersHelper.scala, app/views/isSampleHazardous.scala.html, conf/app.routes, conf/messages.en, test/unit/controllers/IsSampleHazardousControllerSpec.scala, test/unit/models/oCase.scala, test/unit/utils/CheckYourAnswersHelperSpec.scala, test/unit/views/IsSampleHazardousViewSpec.scala, test/unit/views/behaviours/YesNoViewBehaviours.scala
This ticket adds the new is-sample-hazardous page without any changes to the navigation/journey.
=> DIT-2310 - Added is-sample-hazardous page (content-only)

conf/messages.en
=> DIT-2384 # changed error message on provide bti page.

app/config/FrontendAppConfig.scala, app/views/components/view_application.scala.html, conf/application.conf
This should be merged after 
- https://github.com/hmrc/app-config-qa/pull/9157 
- https://github.com/hmrc/app-config-staging/pull/6663
- https://github.com/hmrc/app-config-production/pull/8761
=> DIT-2417 | Fixed icons not displaying correctly in different environments

app/controllers/CheckYourAnswersController.scala
This seems to be flipped around, whoops
=> DIT-1604 Ensure the 'public' property is set correctly for file attachments

app/config/FrontendAppConfig.scala, app/config/Module.scala, app/connectors/BindingTariffClassificationConnector.scala, app/controllers/CheckYourAnswersController.scala, app/models/CaseUpdate.scala, app/repositories/LockRepoProvider.scala, app/service/CasesService.scala, app/utils/JsonFormatters.scala, app/viewmodels/FileView.scala, app/workers/MigrationWorker.scala, conf/application.conf, project/AppDependencies.scala, test/unit/connectors/BindingTariffClassificationConnectorSpec.scala, test/unit/controllers/CheckYourAnswersControllerSpec.scala, test/unit/models/CasePayloads.scala, test/unit/service/CasesServiceSpec.scala, test/unit/workers/MigrationWorkerSpec.scala
This requires the backend PR https://github.com/hmrc/binding-tariff-classification/pull/168 in order to update the application PDFs.
=> DIT-2618 Add migration worker to regenerate missing application PDFs

app/config/FrontendAppConfig.scala, app/controllers/BTARedirectController.scala, app/controllers/ConfirmationController.scala, app/controllers/ErrorController.scala, app/controllers/IndexController.scala, app/controllers/SignOutController.scala, app/handlers/ErrorHandler.scala, app/models/requests/BTARequest.scala, app/service/BTAUserService.scala, app/viewmodels/ConfirmationUrlViewModel.scala, app/views/GovukLayoutWrapper.scala.html, app/views/account_dashboard_statuses.scala.html, app/views/confirmation.scala.html, build.sbt, conf/app.routes, conf/application.conf, conf/messages.cy, conf/messages.en, test/unit/base/SpecBase.scala, test/unit/controllers/BTARedirectControllerSpec.scala, test/unit/controllers/ConfirmationControllerSpec.scala, test/unit/controllers/ErrorControllerSpec.scala, test/unit/controllers/IndexControllerSpec.scala, test/unit/controllers/SignOutControllerSpec.scala, test/unit/service/BTAUserServiceSpec.scala, test/unit/service/FileServiceSpec.scala, test/unit/viewmodels/ConfirmationUrlViewModelSpec.scala, test/unit/views/AccountDashboardStatusesViewSpec.scala, test/unit/views/ConfirmationViewSpec.scala, test/unit/views/ViewSpecBase.scala
=> DDCE-2785-GET: New Content for BTA users

conf/logback.xml, project/AppDependencies.scala
Update hmrc-mongo-play-28 from 0.67 to 0.68 version
=> DDCE-3223 - Update hmrc-mongo-play-28 from 0.67 to 0.68 version

conf/messages.cy, project/AppDependencies.scala, test/resources/application.conf, test/unit/base/SpecBase.scala, test/unit/controllers/BTARedirectControllerSpec.scala, test/unit/controllers/LanguageSwitchControllerSpec.scala, test/unit/filters/SessionIdFilterSpec.scala, test/unit/utils/UnitSpec.scala, test/unit/views/AccountDashboardStatusesViewSpec.scala, test/unit/workers/MigrationWorkerSpec.scala
Updated messages for changes, manually tested functionality.
Updated possible additional dependencies
Sent email to BA to confirm the changes
=> DDCE 1952 : Welsh language amendments

app/connectors/BindingTariffFilestoreConnector.scala, project/AppDependencies.scala, test/unit/connectors/BindingTariffFilestoreConnectorSpec.scala
=> [DDCE-3516] Unsigned S3 Urls removed, and dependency upgrades

app/controllers/RegisteredAddressForEoriController.scala, app/views/components/input_number.scala.html, app/views/components/input_text.scala.html, app/views/components/select.scala.html, app/views/components/show_rulings_table.scala.html, app/views/components/view_application.scala.html, app/views/confirmation.scala.html, app/views/enterContactDetails.scala.html, app/views/registeredAddressForEori.scala.html, test/unit/utils/UnitSpec.scala, test/unit/views/ConfirmationViewSpec.scala
=> DDCE-3492 Fixing accessibility errors

app/config/Module.scala, app/controllers/AccumulatingAnswerEditing.scala, app/controllers/AnswerCaching.scala, app/controllers/AnswerCachingController.scala, app/controllers/SupportingMaterialFileListController.scala, app/filters/SessionIdFilter.scala, app/models/Paged.scala, build.sbt, project/plugins.sbt, test/unit/controllers/behaviours/AnswerCachingControllerBehaviours.scala, test/unit/forms/EnterContactDetailsFormProviderSpec.scala
=> DDCE-3551: upgrade to Scala 2.13

app/controllers/AccumulatingAnswerEditing.scala, app/controllers/AnswerCaching.scala, app/forms/mappings/Formatters.scala, build.sbt, project/AppDependencies.scala, project/build.properties, scalastyle-config.xml
=> DDCE-3668 Upgrade binding-tariff-trader-frontend to jdk 11

app/config/FrontendAppConfig.scala, app/views/GovukLayoutWrapper.scala.html, conf/application.conf
Add research banner, make it configurable so it can be disabled in the future
=> DDCE-3835: Add research banner

README.md, project/AppDependencies.scala, project/plugins.sbt
=> DDCE-4515 Upgrade ATaR to use sm2

app/views/check_your_answers.scala.html, app/views/enterContactDetails.scala.html, app/views/howWeContactYou.scala.html, build.sbt, conf/application.conf, conf/messages.cy, conf/messages.en, project/AppDependencies.scala
=> DDCE-4550 ATaR content changes

app/controllers/CheckYourAnswersController.scala, app/controllers/ConfirmationController.scala, app/controllers/IndexController.scala, app/models/UserAnswers.scala, app/service/BTAUserService.scala, app/service/UserAnswerDeletionService.scala, app/viewmodels/ConfirmationUrlViewModel.scala, app/views/account_dashboard_statuses.scala.html, app/views/components/button_link.scala.html, app/views/confirmation.scala.html, conf/app.routes, project/AppDependencies.scala, test/controllers/AddAnotherRulingControllerSpec.scala, test/controllers/ConfirmationControllerSpec.scala, test/controllers/ControllerSpecBase.scala, test/controllers/IndexControllerSpec.scala, test/service/UserAnswerDeletionServiceSpec.scala, test/viewmodels/ConfirmationUrlViewModelSpec.scala, test/views/ConfirmationViewSpec.scala
~~note to self add tests for new submit routes on index page and confirmation page.~~
=> DDCE-5258 Add new page deletion mechanism and routes to preserve necessary data to fix translation toggle

.gitignore, app/service/PdfGeneratorService.scala, app/views/components/fop/hmrc-frontend-fop-matchers.xsl, app/views/components/fop/view_application.xml, test/service/PdfGeneratorServiceSpec.scala
- To allow XLST to read files in other environments when generating PDFs
=> DDCE-5596: Provide XSLT with URIResolver for Apache FOP

app/views/components/submit_button.scala.html
1.  Changed custom button to a govUkButton
2. Implemented preventDoubleClick function
=> DDCE-6659: Prevent Multiple Submissions on 'Accept and apply for a ruling' Button
